# Dockerfile.nginx
FROM nginx:alpine

RUN mkdir -p /taiga/media /taiga/static /taiga/protected

COPY config/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

RUN ls -la /etc/nginx/conf.d/ && \
    echo "Content of nginx config:" && \
    cat /etc/nginx/conf.d/default.conf || echo "Config file not found!"
