version: "3.8"

services:
  # Stateful Services (Should always be separate)
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data
    # ... config ...

  rabbitmq:
    image: rabbitmq:3-management-alpine
    # ... config ...

  # Application Services (Could be combined)
  backend:
    image: taiga-combined-backend  # Custom image combining backend + protected
    depends_on:
      - db
      - rabbitmq
    volumes:
      - media_data:/app/media
    # ... config ...

  frontend:
    image: taiga-combined-frontend  # Custom image combining frontend + nginx
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - media_data:/app/media:ro
    # ... config ...

volumes:
  db_data:
  media_data:
